# Generated by Django 5.2.3 on 2025-07-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='preparation_time',
            field=models.PositiveIntegerField(default=15, help_text='Preparation time in minutes'),
            preserve_default=False,
        ),
    ]
